import type {
  Chore,
  ChoreCheckIn,
  Expense,
  MonthlySharedBalance,
  Reward,
  SharedTodo,
  User,
  WishlistItem,
} from "./types";

export const users: User[] = [
  {
    id: "user-b",
    name: "B",
    initials: "B",
    avatarColor: "bg-[var(--partner-b)] text-[var(--bg-card)]",
    role: "partner",
    points: 184,
  },
  {
    id: "user-annie",
    name: "Annie",
    initials: "A",
    avatarColor: "bg-[var(--partner-a)] text-[var(--bg-card)]",
    role: "partner",
    points: 201,
  },
];

export const sharedTodos: SharedTodo[] = [
  {
    id: "todo-dental",
    title: "Dental",
    notes: "Bring insurance card and arrive 10 minutes early.",
    assignedTo: "user-b",
    dueDate: "2026-04-30",
    dueTime: "12:30pm",
    status: "todo",
    priority: "high",
    tags: ["appointment", "health"],
  },
  {
    id: "todo-physio",
    title: "Physio appointment",
    notes: "Wear comfortable shoes for mobility exercises.",
    assignedTo: "user-annie",
    dueDate: "2026-05-01",
    dueTime: "9:15am",
    status: "todo",
    priority: "high",
    tags: ["appointment", "health"],
  },
  {
    id: "todo-meal-plan",
    title: "Plan weekday dinners",
    assignedTo: "both",
    dueDate: "2026-05-02",
    status: "in_progress",
    priority: "medium",
    tags: ["home", "food"],
  },
  {
    id: "todo-call-landlord",
    title: "Call landlord about loose window handle",
    assignedTo: "user-b",
    dueDate: "2026-05-03",
    status: "todo",
    priority: "medium",
    tags: ["home"],
  },
  {
    id: "todo-buy-card",
    title: "Pick up birthday card for Mia",
    assignedTo: "user-annie",
    dueDate: "2026-05-04",
    status: "done",
    priority: "low",
    tags: ["family"],
  },
];

export const chores: Chore[] = [
  {
    id: "chore-dishes",
    title: "Washing dishes",
    description: "Clear the sink, wipe counters, and start the dishwasher.",
    points: 8,
    assignedTo: "user-b",
    status: "claimed",
    frequency: "daily",
    estimatedMinutes: 15,
  },
  {
    id: "chore-cooking",
    title: "Cooking",
    description: "Cook dinner and pack any leftovers for tomorrow.",
    points: 14,
    assignedTo: "user-annie",
    status: "claimed",
    frequency: "daily",
    estimatedMinutes: 45,
  },
  {
    id: "chore-trash",
    title: "Taking trash out",
    description: "Take kitchen trash and recycling to the bins downstairs.",
    points: 6,
    assignedTo: "open",
    status: "available",
    frequency: "as_needed",
    estimatedMinutes: 8,
  },
  {
    id: "chore-cleaning",
    title: "Cleaning",
    description: "Vacuum living room, tidy coffee table, and dust shelves.",
    points: 18,
    assignedTo: "user-b",
    status: "completed",
    frequency: "weekly",
    estimatedMinutes: 50,
  },
  {
    id: "chore-laundry",
    title: "Fold laundry",
    description: "Fold clean laundry and put clothes away.",
    points: 10,
    assignedTo: "user-annie",
    status: "available",
    frequency: "weekly",
    estimatedMinutes: 25,
  },
];

export const choreCheckIns: ChoreCheckIn[] = [
  {
    id: "checkin-001",
    choreId: "chore-cleaning",
    userId: "user-b",
    checkedInAt: "2026-04-29T19:20:00-04:00",
    pointsEarned: 18,
    mood: "hard",
    note: "Deep cleaned under the sofa too.",
  },
  {
    id: "checkin-002",
    choreId: "chore-cooking",
    userId: "user-annie",
    checkedInAt: "2026-04-29T20:05:00-04:00",
    pointsEarned: 14,
    mood: "normal",
    note: "Made pasta and salad.",
  },
  {
    id: "checkin-003",
    choreId: "chore-dishes",
    userId: "user-b",
    checkedInAt: "2026-04-30T08:10:00-04:00",
    pointsEarned: 8,
    mood: "easy",
  },
  {
    id: "checkin-004",
    choreId: "chore-trash",
    userId: "user-annie",
    checkedInAt: "2026-04-30T08:25:00-04:00",
    pointsEarned: 6,
    mood: "easy",
  },
];

export const expenses: Expense[] = [
  {
    id: "expense-dinner",
    title: "Dinner at Little Ruby's",
    amount: 74.8,
    currency: "USD",
    paidBy: "user-annie",
    split: "equal",
    category: "food",
    date: "2026-04-26",
    settled: false,
    notes: "Date night dinner and dessert.",
  },
  {
    id: "expense-rent",
    title: "Rent",
    amount: 2480,
    currency: "USD",
    paidBy: "user-b",
    split: "equal",
    category: "home",
    date: "2026-04-28",
    settled: true,
  },
  {
    id: "expense-groceries",
    title: "Groceries",
    amount: 126.35,
    currency: "USD",
    paidBy: "user-b",
    split: "equal",
    category: "food",
    date: "2026-04-29",
    settled: false,
    notes: "Trader Joe's weekly shop.",
  },
  {
    id: "expense-physio-copay",
    title: "Physio co-pay",
    amount: 35,
    currency: "USD",
    paidBy: "user-annie",
    split: "paid_by_annie",
    category: "health",
    date: "2026-05-01",
    settled: true,
  },
  {
    id: "expense-subway",
    title: "Subway cards top-up",
    amount: 44,
    currency: "USD",
    paidBy: "user-b",
    split: "equal",
    category: "transport",
    date: "2026-04-25",
    settled: true,
  },
  {
    id: "expense-shopping",
    title: "Home basics at Target",
    amount: 68.9,
    currency: "USD",
    paidBy: "user-annie",
    split: "equal",
    category: "shopping",
    date: "2026-04-24",
    settled: false,
    notes: "Candles, hand soap, and storage bins.",
  },
  {
    id: "expense-entertainment",
    title: "Cinema tickets",
    amount: 38,
    currency: "USD",
    paidBy: "user-b",
    split: "equal",
    category: "fun",
    date: "2026-04-20",
    settled: true,
  },
];

export const monthlySharedBalance: MonthlySharedBalance = {
  month: "April 2026",
  totalIncome: 6200,
  currency: "USD",
};

export const rewards: Reward[] = [
  {
    id: "reward-movie-night",
    title: "Movie night pick",
    description: "Winner chooses the movie and snacks.",
    pointsCost: 40,
    validityDays: 14,
    status: "available",
    createdBy: "user-annie",
  },
  {
    id: "reward-breakfast-bed",
    title: "Breakfast in bed",
    description: "Redeem for a slow weekend breakfast made by your partner.",
    pointsCost: 75,
    validityDays: 21,
    status: "locked",
    createdBy: "user-b",
  },
  {
    id: "reward-spa-evening",
    title: "At-home spa evening",
    description: "Face masks, candles, tea, and no chores for the night.",
    pointsCost: 110,
    validityDays: 30,
    status: "available",
    createdBy: "user-annie",
  },
  {
    id: "reward-tennis-date",
    title: "Saturday tennis date",
    description: "Book a court and grab smoothies after.",
    pointsCost: 90,
    validityDays: 10,
    status: "redeemed",
    createdBy: "user-b",
  },
];

export const wishlistItems: WishlistItem[] = [
  {
    id: "wish-airpods-pro-2",
    title: "AirPods Pro 2",
    category: "tech",
    estimatedPrice: 249,
    currency: "USD",
    requestedBy: "user-b",
    priority: "medium",
    status: "saving",
    savedAmount: 90,
    notes: "For commuting and gym sessions.",
  },
  {
    id: "wish-tennis-racket",
    title: "Tennis racket",
    category: "sport",
    estimatedPrice: 189,
    currency: "USD",
    requestedBy: "user-annie",
    priority: "high",
    status: "ready",
    savedAmount: 189,
    notes: "Lightweight intermediate racket.",
  },
  {
    id: "wish-camera",
    title: "Camera",
    category: "camera",
    estimatedPrice: 799,
    currency: "USD",
    requestedBy: "both",
    priority: "medium",
    status: "saving",
    savedAmount: 260,
    notes: "Compact mirrorless camera for travel photos.",
  },
  {
    id: "wish-perfume",
    title: "Perfume",
    category: "beauty",
    estimatedPrice: 138,
    currency: "USD",
    requestedBy: "user-annie",
    priority: "low",
    status: "idea",
    savedAmount: 0,
    notes: "Soft floral scent for spring.",
  },
  {
    id: "wish-weekend-cabin",
    title: "Weekend cabin stay",
    category: "travel",
    estimatedPrice: 420,
    currency: "USD",
    requestedBy: "both",
    priority: "high",
    status: "saving",
    savedAmount: 150,
  },
];
